server:
  port: 8888
spring:
  application:
    name: blog
  datasource:
    url: jdbc:mysql://localhost:3306/myblog?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: su360595304
  redis:
    host: 192.168.227.134
    database: 0
    port: 6379
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm
  servlet:
    multipart:
      max-file-size: 10MB
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.hu.myblog.entity

aliyun:
  oss:
    endpoint: oss-cn-xxx.aliyuncs.com
    bucket: xxx
    accessKeyId: xxx
    secret: xxx

